### ISSUE TITLE
Update npm package

### ISSUE THREAD

**Issue by PhilippRaab** [lezer-parser/json#4]
I would like to work on the json language support on codemirror 6, but I would need the updated package on npm to add it as a dependency. Could you please update the package?

**Comment by marijnh** [comment]
@satchmorun Could you please give me publish access for the package? (I think `npm owner add marijn lezer-json` would do the trick)

**Comment by satchmorun** [comment]
@marijnh done!

**Comment by marijnh** [comment]
Thank you! There's a version 0.10.0 out now.
