### ISSUE TITLE
HJson support

### ISSUE THREAD

**Issue by stijnb1234** [lezer-parser/json#5]
It would be great if hjson gets added too.
More can be found here: https://hjson.github.io/

Syntax description:
https://hjson.github.io/syntax.html

**Comment by marijnh** [comment]
I think there's too many JSON dialects to start adding support for them to this package. The way to get support for a dialect would be to fork the grammar and maintain a separate package for it.

**Comment by stijnb1234** [comment]
> I think there's too many JSON dialects to start adding support for them to this package. The way to get support for a dialect would be to fork the grammar and maintain a separate package for it.

I see. Where can I suggest this?

**Comment by marijnh** [comment]
You'd have to do it yourself.

**Comment by stijnb1234** [comment]
> You'd have to do it yourself.

Okay. Any documentation on this?
