### ISSUE TITLE
Errors when parsing escape characters

### ISSUE THREAD

**Issue by snnsnn** [lezer-parser/json#6]
Hi, I was trying to parse a string with escape characters, I got parsing errors for the value with escaped double quotes.

The text I was parsing:

```json
{
  "description": "Some description",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "test": "echo \"no test specified\" && exit 1"
  },
  "dependencies": {
    "@lezer/common": "^1.2.1"
  }
}
```

The code I used to check for a parsing error:

```ts
if (node.type.isError) {
  console.log(code.slice(from, to));
}
```

I go three logs on the console output (I removed the line numbers for clarity):

```
no
test
specified" && exit 1"
```

I am not sure if I overlook something or I should escape the escape character itself first, like so:

```"echo \\"no test specified\\" && exit 1"```

Thank you for your time.

**Comment by marijnh** [comment]
This code parses without any errors for me in @lezer/json 1.0.2:

```
JsonText(Object("{",
  Property(PropertyName,String),
  Property(PropertyName,Array("[","]")),
  Property(PropertyName,String),
  Property(PropertyName,String),
  Property(PropertyName,Object("{",Property(PropertyName,String),"}")),
  Property(PropertyName,Object("{",Property(PropertyName,String),"}")),
"}"))
```

**Comment by snnsnn** [comment]
Here is the code I used.

```ts
import { parser } from '@lezer/json';

const jsonParser = parser.configure({});

const code = `{
  "description": "Some description",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "test": "echo \"no test specified\" && exit 1"
  },
  "dependencies": {
    "@lezer/common": "^1.2.1"
  }
}`;

const tree = jsonParser.parse(code);

const cursor = tree.cursor();

cursor.iterate((nodeRef) => {
  const { from, to, node } = nodeRef;
  if (node.type.isError) {
    console.error(code.slice(from, to));
  }
});
```

I created an online demo https://stackblitz.com/edit/vitejs-vite-6bb2yn?file=src%2Fmain.ts in case you might want to inspect the code I used.

**Comment by marijnh** [comment]
You should double-escape those backslashes if you're using them in a JavaScript string literal. I.e. the problem is that your `code` string in that test code doesn't contain any actual backslashes.
